# Generated by Django 5.0.2 on 2024-02-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='adult',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='children',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='infants',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
